### ISSUE TITLE
Service call

### ISSUE THREAD

**Issue by reesion** [jnimmo/hass-intesisbox#18]
Hi

I am having issue with service call to turn off the device. It doesn’t seem to work

when I use service: climate.turn_off it is giving me unknown error. 

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/intesisbox/climate.py:229 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 03:43:56 (4 occurrences) 
Last logged: 03:52:30

[140440224955216] Error handling message: Unknown error
[140440223523552] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 552, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1243, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 349, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 367, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 570, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 520, in async_turn_off
    await self.hass.async_add_executor_job(self.turn_off)  # type: ignore[attr-defined]
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/intesisbox/climate.py", line 229, in turn_off
    self.set_operation_mode(HVAC_MODE_OFF)
AttributeError: 'IntesisBoxAC' object has no attribute 'set_operation_mode'

**Comment by jedney** [comment]
For automation I was able to get it working with: A device action, using the Intesisbox as the device, with "Change HVAC mode on Heat Pump" set to "off".

**Comment by jedney** [comment]
Yep. Worked for me.

**Comment by tathamoddie** [comment]
This has been merged in via 235cd6210464075f8bed3fb5e889543164d0dabc, so you should be able to close this issue now.
