### ISSUE TITLE
Integration failed to connect

### ISSUE THREAD

**Issue by reesion** [jnimmo/hass-intesisbox#38]
Hi,

I have this integration setup for a while. Have been working fine until the recent HA and intesisbox updates.

I have tried to re-install the addon and resetup the integration but it is still the same.

Logs below.

2023-04-05 11:46:35.497 INFO (MainThread) [homeassistant.setup] Setting up intesisbox
2023-04-05 11:46:35.497 INFO (MainThread) [homeassistant.setup] Setup of domain intesisbox took 0.0 seconds
2023-04-05 11:46:35.498 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Opening connection to IntesisBox 192.168.1.80:3310
2023-04-05 11:46:35.506 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1076, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1060, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 969, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 501, in sock_connect
    return await fut
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 541, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.1.80', 3310)

2023-04-05 12:02:23.203 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.1.80 for intesisbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/intesisbox/__init__.py", line 21, in async_setup_entry
    await asyncio.sleep(0.1)
  File "/usr/local/lib/python3.10/asyncio/tasks.py", line 605, in sleep
    return await future
asyncio.exceptions.CancelledError

**Comment by tathamoddie** [comment]
The integration is failing to open a TCP connection to `192.168.1.80:3310`

Can you telnet to the Intesis box manually?

From a command line, you should be able to:
1. Run `telnet 192.168.1.80 3310`, and see it say "Connected to 192.168.1.80"
3. Then type `PING` and press enter, and see a result like `PING:-70`

If you're on Windows, and don't have the telnet package installed, you can:
1. Launch Windows PowerShell
2. Run `Test-NetConnection -ComputerName 192.168.1.80 -Port 3310`
3. See `TcpTestSucceeded : True`

I suspect your Intensis box is offline, on a different IP address, or there is a routing issue between HA and the box.

**Comment by tathamoddie** [comment]
That's not the issue that the original poster was having, based on the logs that they supplied. Their logs are already past the platform setup stage, and up to the point of the connection being attempted.
