### ISSUE TITLE
2nd unit is not loading 

### ISSUE THREAD

**Issue by sbosman84** [jnimmo/hass-intesisbox#48]
Hi,

I've two airconditioning units connected to the airconwithme platform. And when adding the integration via the wizard in Home Assistant I only see 1 of the units appearing in HA. And the other unit has the following error message in the logs:

`Logger: homeassistant.components.climate
Source: custom_components/intesishome/climate.py:358
Integration: Klimaat (documentation, issues)
First occurred: 20:25:18 (1 occurrences)
Last logged: 20:25:18

intesishome: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 576, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 938, in async_device_update
    await self.async_update()
  File "/config/custom_components/intesishome/climate.py", line 358, in async_update
    self._current_temp = self._controller.get_temperature(self._device_id)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyintesishome/intesisbase.py", line 403, in get_temperature
    temperature = self.get_device_property(device_id, "temperature")
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyintesishome/intesisbase.py", line 193, in get_device_property
    return self._devices[str(device_id)].get(property_name)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: '224571441711392'`

Any suggestion on where to look at?

**Comment by jnimmo** [comment]
Hi there, out of interest are you treating the latest pre-release version, https://github.com/jnimmo/hass-intesishome/releases/tag/1.0.6

**Comment by sbosman84** [comment]
Ah apologies, I just noticed that there are 2 repositories (1 with the config flow and 1 without). I'm on the 1.0.5 release from the repository with the config flow so not this one. I will try the 1.0.6 release as well and get back to you.

Just found that I had created an issue over there as well. So after I've tested the 1.0.6 release I will close this issue.
