### ISSUE TITLE
Unable to prepare setup for platform 'intesisbox.climate'

### ISSUE THREAD

**Issue by nhatmdoan** [jnimmo/hass-intesisbox#52]
Hi,
I have been using the integration for over 1 year. It has been fantastic until today.

Today, I updated home assistant:
Core 2024.1.3
Supervisor 2023.12.0
Operating System 11.4
Frontend 20240104.0

And updated hass-intesisbox to the latest version.

When I re-added my boxes. the boxes was added but there is no entity or device in them.
<img width="700" alt="Screenshot at Jan 16 11-29-17" src="https://github.com/jnimmo/hass-intesisbox/assets/145981442/e2848d56-6e51-4c50-b837-e140a8a80101">

I got this from the log:
```
Logger: homeassistant.setup
Source: setup.py:403
First occurred: 11:38:33 AM (2 occurrences)
Last logged: 11:38:33 AM

Unable to prepare setup for platform 'intesisbox.climate': Platform not found (cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)).
```

And this:

```
Logger: homeassistant.config
Source: config.py:1483
First occurred: 11:38:32 AM (1 occurrences)
Last logged: 11:38:32 AM

Platform error: climate - cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config.py", line 1483, in async_process_component_config
    platform = p_integration.get_platform(domain)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/intesisbox/climate.py", line 37, in <module>
    from homeassistant.helpers.typing import ConfigEntry, ConfigType, DiscoveryInfoType
ImportError: cannot import name 'ConfigEntry' from 'homeassistant.helpers.typing' (/usr/src/homeassistant/homeassistant/helpers/typing.py)
```

I was wondering if anyone has the same issue and knows how to fix it. Thanks.

**Comment by Glirido** [comment]
Try to update hass-intesisbox to exact release 2.0.0.
It looks like the last commits since then have broken something.

**Comment by luismalddonado** [comment]
In version [v2.0.1] this should be fixed now

**Comment by jbergler** [comment]
@nhatmdoan based on the last few comments I'm going to close this, but if your issue isn't fixed please let me know and we can re-open the issue.
