### ISSUE TITLE
Intesis box setup fails

### ISSUE THREAD

**Issue by Francois3d** [jnimmo/hass-intesisbox#62]
I cant to get the intesis box setup on my home assistant. It fails with a unknown error and says check logs. Any ideas if I am doing something wrong.

logs:

logger:%20homeassistant.config_entries%0ASource%3A%20config_entries.py%3A604%0AFirst%20occurred%3A%2002%3A38%3A13%20(3%20occurrences)%0ALast%20logged%3A%2003%3A00%3A54%0A%0AError%20setting%20up%20entry%2010.0.0.36%20for%20intesisbox%0ATraceback%20(most%20recent%20call%20last)%3A%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/config_entries.py%22,%20line%20604,%20in%20async_setup%0A%20%20%20%20result%20=%20await%20component.async_setup_entry(hass,%20self)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/intesisbox/__init__.py%22,%20line%2022,%20in%20async_setup_entry%0A%20%20%20%20await%20asyncio.sleep(0.1)%0A%20%20File%20%22/usr/local/lib/python3.12/asyncio/tasks.py%22,%20line%20665,%20in%20sleep%0A%20%20%20%20return%20await%20future%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0Aasyncio.exceptions.CancelledError:%20Global%20task%20timeout%0A

**Comment by max-unthan** [comment]
I have a similar issue, i add the Host IP and nothing happens. Till the Setup crashes.
I did Test it a few months ago, back then it was setup easily and successfull.

Any Ideas? 

![{286F96B8-911F-4AF8-8F9A-E49DA33BFEF6}](https://github.com/user-attachments/assets/26576e4e-0e08-4804-8e7f-57d2fbce93bd)

**Comment by RustyKnight** [comment]
New to HA, thought I'd give it a try.  I also ran into a connection issue.  I can navigate to the boxes UI from a web browser without issue (admin/admin)

```
Device Model: IS-IR-WIFI-1
Device Firmware Version: 1.5.0; 1.3.3; 2.3; 1.0.3.0
Wireless Firmware Version: 1.2.0
```

```
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:112
First occurred: 7:15:07 PM (1 occurrences)
Last logged: 7:15:07 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1161, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1136, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
        exceptions, addrinfo, laddr_infos)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1039, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 641, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/selector_events.py", line 681, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.68.55', 3310)
```

Maybe it's a port issue?  Not familiar without the WMP(?) protocol.

Anyways, thanks for making an effort!

**Comment by jnimmo** [comment]
Hi @RustyKnight - you need jnimmo/hass-intesishome rather than IntesisBox

**Comment by RustyKnight** [comment]
@jnimmo Thanks for making the time to reply.  I did try and wasn't able to get it to work.  I'll give it another try and see where it takes me.
