### ISSUE TITLE
Connection exception results in failed reconnection attempts

### ISSUE THREAD

**Issue by Glirido** [jnimmo/hass-intesisbox#64]
Last weeks integration has been failing quite a bit.
I've been collecting logs to see what happens:

```
    2024-12-12 07:11:31.789 DEBUG (MainThread) [custom_components.intesisbox.climate] Intesisbox sent a status update.
    2024-12-12 07:11:45.382 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Sending keepalive
    2024-12-12 07:11:45.383 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Data sent: 'PING'
    2024-12-12 07:11:45.397 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Data received: 'PONG:-58'
    2024-12-12 07:12:30.384 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Sending keepalive
    2024-12-12 07:12:30.386 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Data sent: 'PING'
    2024-12-12 07:12:44.059 INFO (MainThread) [custom_components.intesisbox.intesisbox] The server closed the connection
    2024-12-12 07:12:44.059 DEBUG (MainThread) [custom_components.intesisbox.climate] Intesisbox sent a status update.
    2024-12-12 07:12:54.069 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.xxx is taking over 10 seconds
    2024-12-12 07:13:15.387 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Not connected, skipping keepalive
    2024-12-12 07:13:44.069 DEBUG (SyncWorker_41) [custom_components.intesisbox.intesisbox] Opening connection to IntesisBox 192.168.1.123:3310
    2024-12-12 07:13:44.071 DEBUG (MainThread) [custom_components.intesisbox.climate] Lost connection to Intesisbox.
    2024-12-12 07:13:58.344 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1122, in create_connection
        raise exceptions[0]
      File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1104, in create_connection
        sock = await self._connect_sock(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1007, in _connect_sock
        await self.sock_connect(sock, address)
      File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 641, in sock_connect
        return await fut
               ^^^^^^^^^
      File "/usr/local/lib/python3.12/asyncio/selector_events.py", line 681, in _sock_connect_cb
        raise OSError(err, f'Connect call failed {address}')
    OSError: [Errno 113] Connect call failed ('192.168.x.x', 3310)
    2024-12-12 07:14:30.379 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Not connected, skipping poll_status()
    2024-12-12 07:16:31.772 DEBUG (MainThread) [custom_components.intesisbox.intesisbox] Not connected, skipping poll_status()
    2024-12-12 07:17:44.071 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.xxx is taking over 10 seconds
    2024-12-12 07:18:34.072 DEBUG (SyncWorker_22) [custom_components.intesisbox.intesisbox] connect() called but already connecting
    2024-12-12 07:22:44.073 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.xxx is taking over 10 seconds
    2024-12-12 07:23:34.072 DEBUG (SyncWorker_3) [custom_components.intesisbox.intesisbox] connect() called but already connecting
    2024-12-12 07:27:44.075 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.xxx is taking over 10 seconds
    2024-12-12 07:28:34.074 DEBUG (SyncWorker_35) [custom_components.intesisbox.intesisbox] connect() called but already connecting
    2024-12-12 07:32:44.076 WARNING (MainThread) [homeassistant.helpers.entity] Update of climate.xxx is taking over 10 seconds
```

Its seems that exception results in code not trying to reconnect because _connectionStatus variable stalls in  API_CONNECTING state forever and always exiting through this line of code:

https://github.com/jnimmo/hass-intesisbox/blob/43d9f4f1385539ffd5725bef604fd718bfc1973d/custom_components/intesisbox/intesisbox.py#L211

And with this loop of connect->skip connect->connect->skip connect the integration is not updating home assistant that complains with "Update of climate.xxx is taking over 10 seconds"

I'm not a python dev but think that exception is being handled by homeassistant core instead of intesisbox try-catch in connect() function, so _connectionStatus is set to API_CONNECTING first time and never switch to API_DISCONNECTED.

Regards,

**Comment by Glirido** [comment]
I forgot to mention that it seems related to issue #50

**Comment by zeg064** [comment]
I've forked this as I was having issues with maintaining a connection for more that a few hours. and wanted to experiment with varying the polling times. Nothing was working so I looked harder and I think there is an issue with this line.

https://github.com/jnimmo/hass-intesisbox/blob/43d9f4f1385539ffd5725bef604fd718bfc1973d/custom_components/intesisbox/intesisbox.py#L202

I think it is missing 'asyncio' . I've changed it in my fork and I've been connected for the longest time yet. This is what mine looks like.

                    _ = asyncio.ensure_future(coro, loop=self._eventLoop)

**Comment by Glirido** [comment]
Sorry @zeg064 but after some testing your change is not working for me. Still hangs when there is a wifi reconnection or AC power cycle.

But i have uploaded a fix into my fork that makes reconnections work. I was testing it for a few weeks and seems that HA doesn't lost control of AC like before. Maybe it could help.

**Comment by zeg064** [comment]
Thanks @Glirido. I came to same conclusion only a few hours ago when my connection failed again. I'll take a look at your fix.
